import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

export const ACTIVITY_START = "<!-- AUTO:ACTIVITY:START -->";
export const ACTIVITY_END = "<!-- AUTO:ACTIVITY:END -->";

function escapeCell(value) {
  return String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
}

function badgeSegment(value) {
  return encodeURIComponent(String(value).replaceAll("-", "--").replaceAll("_", "__").replaceAll(" ", "_"));
}

function renderLinks(links) {
  return links.map((link) => {
    const filename = `social-${link.label.toLowerCase()}.svg`;
    return `  <a href="${link.url}"><img alt="${link.label}" src="assets/badges/${filename}" height="36"></a>`;
  }).join("\n");
}

function renderFocus(focus) {
  return [
    "| Area | What I am exploring |",
    "| --- | --- |",
    ...focus.map((item) => `| **${escapeCell(item.name)}** | ${escapeCell(item.description)} |`)
  ].join("\n");
}

function renderProjects(projects) {
  return [
    "| Project | Focus | Why it matters |",
    "| --- | --- | --- |",
    ...projects.map((project) => {
      const homepage = project.homepage ? ` [Live](${project.homepage})` : "";
      return `| [**${escapeCell(project.name)}**](${project.url}) | ${escapeCell(project.focus)} | ${escapeCell(project.summary)}${homepage} |`;
    })
  ].join("\n");
}

function extractActivity(readme) {
  const startIndex = readme.indexOf(ACTIVITY_START);
  const endIndex = readme.indexOf(ACTIVITY_END);
  if (startIndex === -1 || endIndex === -1 || endIndex <= startIndex) return null;
  return readme.slice(startIndex + ACTIVITY_START.length, endIndex).trim();
}

async function readExistingActivity(readmePath) {
  try {
    const existing = await readFile(readmePath, "utf8");
    return extractActivity(existing);
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}

export async function generateProfileReadme({ config, manifest, readmePath }) {
  const existingActivity = await readExistingActivity(readmePath);
  const activity = existingActivity || "_Recent public activity will appear here after the workflow runs._";
  const activitySection = config.activity.enabled
    ? `\n## Recent Activity\n\n${ACTIVITY_START}\n${activity}\n${ACTIVITY_END}\n`
    : "";
  const techStack = config.techStack.map((item) => `\`${item}\``).join(" · ");
  const about = config.profile.about.join("\n\n");

  const readme = `<!-- Generated by GitHub Profile Agent Console. Edit profile.config.json, then run npm run generate. -->
<p align="center">
  <img src="https://readme-typing-svg.demolab.com?font=Courier+New&amp;weight=500&amp;size=15&amp;pause=1000&amp;color=22D3EE&amp;center=true&amp;vCenter=true&amp;width=800&amp;repeat=false&amp;lines=Icarus+laughed+as+he+fell%2C+for+he+knew+to+fall+means+to+have+once+soared." alt="Quote" />
</p>

<p align="center">
  <picture>
    <source media="(max-width: 760px) and (prefers-color-scheme: dark)" srcset="./assets/hero/${manifest.assets.mobileDark}">
    <source media="(max-width: 760px)" srcset="./assets/hero/${manifest.assets.mobileLight}">
    <source media="(prefers-color-scheme: dark)" srcset="./assets/hero/${manifest.assets.desktopDark}">
    <source media="(prefers-color-scheme: light)" srcset="./assets/hero/${manifest.assets.desktopLight}">
    <img src="./assets/hero/${manifest.assets.desktopDark}" alt="${config.profile.name} - ${config.profile.headline}" width="100%">
  </picture>
</p>

<p align="center">
${renderLinks(config.links)}
</p>

<div align="center">
  <img src="https://capsule-render.vercel.app/api?type=transparent&amp;fontColor=22D3EE&amp;height=50&amp;section=header&amp;text=GitHub%20Analytics&amp;fontSize=24&amp;fontAlignY=40" />
</div>
  <p align="center">
    <img width="419" src="https://github-stats-extended.vercel.app/api?username=${config.profile.username}&card_width=419&show_icons=true&hide=issues&title_color=22D3EE&text_color=E5E7EB&icon_color=38BDF8&bg_color=07111F&border_color=22D3EE" />
    <img width="419" src="https://github-stats-extended.vercel.app/api/top-langs/?username=${config.profile.username}&layout=compact&card_width=419&title_color=22D3EE&text_color=E5E7EB&bg_color=07111F&border_color=22D3EE" />
  </p>
<p align="center">
  <img width="100%" src="https://github-readme-activity-graph.vercel.app/graph?username=${config.profile.username}&amp;bg_color=07111F&amp;color=22D3EE&amp;line=38BDF8&amp;point=E5E7EB&amp;area=true&amp;border_color=22D3EE" />
</p>

<div align="center">
  <img src="https://capsule-render.vercel.app/api?type=transparent&amp;fontColor=22D3EE&amp;height=50&amp;section=header&amp;text=Featured%20Projects&amp;fontSize=24&amp;fontAlignY=40" />
</div>
<p align="center">
  <img src="assets/projects.svg" alt="Featured Projects" />
</p>

<div align="center">
  <img src="https://capsule-render.vercel.app/api?type=transparent&amp;fontColor=22D3EE&amp;height=50&amp;section=header&amp;text=Tech%20Stack&amp;fontSize=24&amp;fontAlignY=40" />
</div>
<p align="center">
  <img src="assets/badges/python.svg" height="36" />
  <img src="assets/badges/pytorch.svg" height="36" />
  <img src="assets/badges/tensorflow.svg" height="36" />
  <img src="assets/badges/scikit-learn.svg" height="36" />
  <img src="assets/badges/typescript.svg" height="36" />
  <img src="assets/badges/nextjs.svg" height="36" />
</p>

<div align="center">
  <img src="https://capsule-render.vercel.app/api?type=transparent&amp;fontColor=22D3EE&amp;height=50&amp;section=header&amp;text=AI%20Tools&amp;fontSize=24&amp;fontAlignY=40" />
</div>
<p align="center">
  <img src="assets/badges/antigravity.svg" height="36" />
  <img src="assets/badges/claude.svg" height="36" />
  <img src="assets/badges/stitch.svg" height="36" />
  <img src="assets/badges/manus.svg" height="36" />
  <img src="assets/badges/lovable.svg" height="36" />
  <img src="assets/badges/git.svg" height="36" />
  <img src="assets/badges/github.svg" height="36" />
</p>
`;

  await writeFile(resolve(readmePath), readme);
  return readme;
}
